#!/bin/bash
# Program to output a system information page
title="System Information Report for $HOSTNAME"
timestamp=$(date)

print_hello () {
cat << EOF
$(echo "Hello")
EOF
return
}

echo "<html>
<head>
<title>$title</title>
</head>
<body>
<p>$(print_hello)</p>                                                                                                                                                                
</body>
</html> "

